package com.spring.spring_crud.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a User in the system.
 * This class is mapped to a database table using JPA annotations.
 */
@Data
@Entity // Specifies that the class is an entity and is mapped to a database table.
@NoArgsConstructor // Generates a no-argument constructor.
@AllArgsConstructor // Generates a constructor with all fields as parameters.
public class User {

    /**
     * The unique identifier for the user.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The name of the user.
     */
    private String name;

    /**
     * The age of the user.
     */
    private Integer age;

    /**
     * The address of the user.
     */
    private String address;
}
